### ISSUE TITLE
SQL Server 2016 causes 'System.Exception: Unsupported Server Version'

### ISSUE THREAD

**Issue by SirFrostingham** [billgraziano/ScriptSqlConfig#14]
1. Run gacutil.exe from local system:
```
E:\DB_scripts>gacutil /l Microsoft.SqlServer.Smo
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:
  Microsoft.SqlServer.Smo, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL
  Microsoft.SqlServer.Smo, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL
  Microsoft.SqlServer.Smo, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL
  Microsoft.SqlServer.Smo, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL
  Microsoft.SqlServer.Smo, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL

Number of items = 5
```
2. Edit ScriptSqlConfig.exe.config -> uncomment out `<runtime/>` section

3. Change all `newVersion` attributes from '10.0.0.0' to '14.0.0.0'

4. Run tool pointed at local (also tested remote) SQL 2016 server: 
`ScriptSqlConfig.exe /server localhost /dir e:\db_scripts\generated_db_scripts`

Result:

```
Launching (2012.5)....
Directory: e:\db_scripts\generated_db_scripts
Server: localhost
SMO Version: 14.0.0.0
Scripting Instance information...

Unhandled Exception: System.Exception: Unsupported Server Version
   at ScriptSqlConfig.Program.GetTargetServerVersion(Server srv)
   at ScriptSqlConfig.Program.ScriptInstance(String server, String directory)
   at ScriptSqlConfig.Program.Main(String[] args)
```

Note: This example uses the latest release of the ScriptSqlConfig tool (https://github.com/billgraziano/ScriptSqlConfig/releases/tag/v2012.5).

**Comment by SirFrostingham** [comment]
I worked around this by running the source code locally with the program parameters specified in the project properties -> DEBUG tab -> Command Arguments. In fact, it used the default 'Microsoft.SqlServer.Smo, Version=11.0.0.0' reference. It worked while pointed to my local SQL 2016 server and a remote SQL 2016 server.

There was 1 hiccup, where on the local SQL server, advanced options were not turned on... To fix that, I ran the following SQL script:
```
sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO
sp_configure 'Agent XPs', 1;
GO
RECONFIGURE
GO
```

**Comment by s3rv3radm1n** [comment]
Any update on this issue?  I am have the same problem with SQL 2014:

Launching (2012.5)....
Directory: d:\backups
Server: localhost
SMO Version: 12.0.0.0
Scripting Instance information...

Unhandled Exception: System.Exception: Unsupported Server Version
   at ScriptSqlConfig.Program.GetTargetServerVersion(Server srv)
   at ScriptSqlConfig.Program.ScriptInstance(String server, String directory)
   at ScriptSqlConfig.Program.Main(String[] args)

Do we need to update the versions in the build?
if (version == "120")
                return SqlServerVersion.Version120;
